### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by againxx** [andyzeng/3dmatch-toolbox#10]
Hi, I have been using this great 3d descriptor to do some works about 3d matching. But I found that the usage of GPU's memory was growing up increasely. Have you found this phenomenon?

**Comment by andyzeng** [comment]
Hello, does the memory leak occur during training? Or during the demo?

**Comment by againxx** [comment]
During the demo, I just used the demo net to compute descriptors of several hundreds of objects. It seems that the destructor of the Net class doesn't free all the resource of GPU. I finally fixed it up by using singleton pattern to make the Net class constructed only once.
