### ISSUE TITLE
where is makeCorresDataset

### ISSUE THREAD

**Issue by QinZiwen** [andyzeng/3dmatch-toolbox#12]
Hi, I do not find “makeCorresDataset” in 3dmatch-toolbox？
In addition， I want to use mxnet to train my net with TDF. But I don't known how to input TDF to my net？
thanks！

**Comment by andyzeng** [comment]
`makeCorresDataset.m` can be found in [evaluation/keypoint-matching/makeCorresDataset.m](https://github.com/andyzeng/3dmatch-toolbox/blob/master/evaluation/keypoint-matching/makeCorresDataset.m)

The code from this repository saves TDF voxel grids as a flattened array of float values. You can read those into your MXNet data loader and convert/reshape your TDF  into a 3-dimensional array (numpy.ndarray object), convert it into an MXNet NDArray, and pass it into your net (refer to [here](https://mxnet.incubator.apache.org/tutorials/basic/ndarray.html)). Code to compute TDF from mesh, or depth images, 3D point clouds, can be found [here](https://github.com/andyzeng/3dmatch-toolbox/blob/69af229d3dab924c20dc940ae71a48394322dea2/README.md#converting-3d-data-to-tdf-voxel-grids).
