### ISSUE TITLE
showTDF.m error

### ISSUE THREAD

**Issue by happyfrank** [andyzeng/3dmatch-toolbox#3]
I got this error when I run showTDF.m at matlab R2015b.

```
>> showTDF
bicycle000002
Error using pointCloud>validateAndParseInputs (line 775)
The value of 'Color' is invalid. Expected input to be one of these types:

uint8

Instead its type was double.

Error in pointCloud (line 126)
            [xyzPoints, C, nv] = validateAndParseInputs(varargin{:});

Error in showTDF (line 36)
pcshow(pointCloud(visPts,'color',colorPts));
```

**Comment by andyzeng** [comment]
Looks like the point cloud "color" parameter only takes uint8 in Matlab versions 2015b or earlier. Try replacing line 36 with `pcshow(pointCloud(visPts,'color',uint8(round(colorPts.*255))));`

**Comment by happyfrank** [comment]
Thanks, It works.

**Comment by pvmilk** [comment]
Will the toolbox work in the older Matlab? (e.g. 2014a). 
(Any specific reason it would depends on Matlab 2015b or higher)

**Comment by andyzeng** [comment]
Some parts of the visualization and evaluation tools in the toolbox depend on Matlab 2015a or higher for [Matlab's 3D Point Cloud Processing Toolbox](https://www.mathworks.com/help/vision/3-d-point-cloud-processing.html)
