### ISSUE TITLE
Training step question

### ISSUE THREAD

**Issue by happyfrank** [andyzeng/3dmatch-toolbox#4]
Training 3DMatch from RGB-D Reconstructions
My GPU is GTX1080, When I run training step. It has costed one night to iterate 5000 times.
 Is the time cost reasonable?
 By the way,  can this training file (3dmatch-weights-snapshot-137000.marvin) match the scene that I captured or just for the demo your offered?

**Comment by andyzeng** [comment]
Your training time sounds reasonable. Our pre-trained weights (3dmatch-weights-snapshot-137000.marvin) can be used to match the scene that you captured. However, for the best performance we recommend fine-tuning over scenes that are similar to the ones you've captured (w.r.t. environments and your specific depth camera brand).
