### ISSUE TITLE
Converting 3D Data to TDF Voxel Grids

### ISSUE THREAD

**Issue by ghost** [andyzeng/3dmatch-toolbox#6]
Bravo, for your good work.

I have a question. I can use just the algorithm "Converting 3D Data to TDF Voxel Grids" with Windows ?

Thank you,
sincerely.

**Comment by andyzeng** [comment]
Yes, the code for converting 3D data to TDF voxel grids should work on any platform.

**Comment by ghost** [comment]
Thank you very much for your answer sear !

I use the windows platform. you can explain how to use just Mesh2SDF with cude and your code ?

thank you very much

**Comment by andyzeng** [comment]
There's a copy of [GAPS](https://github.com/andyzeng/3dmatch-toolbox/tree/master/gaps) in this repository with visual studio solution files that you can use in Windows to compile the `msh2df` binaries. There are no additional requirements (CUDA is not required).
