### ISSUE TITLE
Problem with Matlab script demo.m

### ISSUE THREAD

**Issue by manhha1402** [andyzeng/3dmatch-toolbox#9]
Hi,
I tried to run the demo instructions. When I run the matlab script, it showed the error:
"Undefined function 'pcread' for input arguments of type 'char'.
Error in demo (line 16)
fragment1PointCloud = pcread(fragment1PointCloudFile); "
I am new to Matlab and using Matlab 2014a. The problem here is that function "pcread" cannot read .ply file, right?
Thank you very much

**Comment by andyzeng** [comment]
Correct. Matlab's function `pcread` (part of the [3D Point Cloud Processing Toolbox](https://www.mathworks.com/help/vision/3-d-point-cloud-processing.html)) was not introduced until version R2015a. Try updating your version of Matlab to 2015a or higher.

**Comment by manhha1402** [comment]
Thanks, I will update the version to test the approach !
